### ISSUE TITLE
Better usage information

### ISSUE THREAD

**Issue by mdempsky** [mdempsky/unbed#3]
$ unbed -help
    Usage of unbed:

    $ unbed x
    2017/04/13 13:57:50 bad spec expression

Users deserve better.

**Comment by mdempsky** [comment]
$ unbed '"container/ring".Foo.Bar'
    panic: interface conversion: types.Object is nil, not *types.TypeName

    goroutine 1 [running]:
    go/types.(*object).Type(...)
            /home/mdempsky/go/src/github.com/mdempsky/unbed/unbed.go:62
    main.main()
            /home/mdempsky/go/src/github.com/mdempsky/unbed/unbed.go:62 +0x98f
